name: Publish

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  publish-preview:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout our working repository
      - uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: 18.15
          cache: yarn
          registry-url: https://npm.pkg.github.com/
          scope: '@chromatic-protocol'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: |
          yarn install
          yarn build
      - uses: chromatic-protocol/action-github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.PR_ACTION_APP_ID }}
          private_key: ${{ secrets.PR_ACTION_PRIVATE }}
      - name: publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ steps.generate-token.outputs.token }}
          publish_dir: ./build
          external_repository: chromatic-protocol/docs-preview
